# bbhost PC port options. Written by the options screen (F10).
[options]
version = "3"
window_mode = "Fullscreen"
vsync = "Off"
frame_cap = "30"
fps_counter = "Off"
fov = "+0%"
camera_distance = "5"
camera_height = "5"
mouse_menu = "On"
mouse_camera = "On"
mouse_sens = "5"
mouse_invert_x = "Off"
mouse_invert_y = "Off"
mouse_auto_rotation = "Off"
draw_cursor = "On"
button_prompts = "Auto"
ssao = "On"
motion_blur = "On"
anti_alias = "On"
depth_of_field = "On"
chromatic_aberration = "On"
bloom = "10"
vignette = "On"
shadow_distance = "x1.0"
ao_strength = "5"
saturation = "5"
fog = "10"
model_detail = "Normal"
resolution = "3840x1080"
skip_logos = "On"
debug_menu = "Off"
debug_camera = "Off"
change_appearance = "On"
rebirth = "On"
five_players = "On"

[keys]
move_forward = "W"
move_back = "S"
move_left = "A"
move_right = "D"
walk = "Left Alt"
roll = "Space"
lock_on = "Q"
attack = "Mouse1"
strong_attack = "V"
strong_modifier = "Left Shift"
transform = "C, Mouse3"
firearm = "X, Mouse2"
blood_vial = "R"
use_item = "F"
interact = "E"
switch_item = "Down"
switch_right = "Right"
switch_left = "Left"
dpad_up = "Up"
gestures = "G"
personal_effects = "T"
look_up = "I"
look_down = "K"
look_left = "J"
look_right = "L"
menu = "Escape"
confirm = "Return"
back = "Backspace"
l3 = "Left Ctrl"
debug_menu = "`"
